In [69]:
import yfinance as yf
import pandas as pd

class TradingStrategy:
    def __init__(self, symbol: "AAPL", start_date: "2018/1/1", end_date: "2023/12/31", budget: float = "5000"):
        """
        Initialize trading strategy with parameters.
        """
        self.symbol = symbol.upper()
        self.start_date = "2018/1/1"
        self.end_date = "2023/12/31"
        self.budget = "5000"
        self.data = None
        self.position = 0
        self.cash = "5000"
        self.trades = []

In [62]:
data = yf.download('AAPL', start="2018-01-01", end="2023-12-31")
data

C:\Users\user\AppData\Local\Temp\ipykernel_3136\2024759451.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download('AAPL', start="2018-01-01", end="2023-12-31")
[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open     Volume
Ticker            AAPL        AAPL        AAPL        AAPL       AAPL
Date
2018-01-02   40.381001   40.390379   39.677744   39.888723  102223600
2018-01-03   40.373959   40.917812   40.310668   40.444285  118071600
2018-01-04   40.561497   40.664642   40.338800   40.446630   89738400
2018-01-05   41.023308   41.110042   40.566192   40.657615   94640000
2018-01-08   40.870926   41.166292   40.772467   40.870926   82271200
...                ...         ...         ...         ...        ...
2023-12-22  191.974670  193.769472  191.349955  193.541392   37149600
2023-12-26  191.429291  192.262235  191.211137  191.984587   28919300
2023-12-27  191.528442  191.875510  189.485739  190.873995   48087700
2023-12-28  191.954849  193.025784  191.548288  192.510145   34049900
2023-12-29  190.913651  192.767946  190.120364  192.272144   42672100

[1509 rows x 5 columns]

In [71]:
def clean_data(self):
        """
        Clean data: remove duplicates and handle missing values by forward filling.
        """
        if self.data is None:
            raise ValueError("❌ No data available. Run fetch_data() first.")

        # Remove duplicate rows (if any)
        before = len(self.data)
        self.data = self.data[~self.data.index.duplicated(keep="first")]
        after = len(self.data)

        # Handle NaN values by forward fill (and backward fill as fallback)
        self.data.ffill(inplace=True)
        self.data.bfill(inplace=True)

        print(f"🧹 Cleaned data: removed {before - after} duplicates, filled NaN values.")
        return self.data

In [92]:
 def compute_moving_averages(self):
        if self.data is None:
            raise ValueError("❌ No data to compute moving averages. Run fetch_data() first.")
        # Compute 50-day and 200-day moving averages
        self.data["MA50"] = self.data["Close"].rolling(window=50).mean()
        self.data["MA200"] = self.data["Close"].rolling(window=200).mean()
        print("📊 Computed 50-day and 200-day moving averages.")
        return self.data

In [96]:
def apply_strategy(self):
        for i in range(1, len(self.data)):
            price = self.data["Close"].iloc[i]
            ma50 = self.data["MA50"].iloc[i]
            ma200 = self.data["MA200"].iloc[i]
            prev_ma50 = self.data["MA50"].iloc[i - 1]
            prev_ma200 = self.data["MA200"].iloc[i - 1]

            
            if prev_ma50 < prev_ma200 and ma50 > ma200 and self.position == 0:
                shares_to_buy = int(self.cash // price)
                if shares_to_buy > 0:
                    self.position = shares_to_buy
                    self.cash -= shares_to_buy * price
                    self.trades.append((self.data.index[i], "BUY", price, shares_to_buy))
                    print(f"🟢 BUY {shares_to_buy} shares at {price:.2f} on {self.data.index[i].date()}")

            
            elif prev_ma50 > prev_ma200 and ma50 < ma200 and self.position > 0:
                self.cash += self.position * price
                self.trades.append((self.data.index[i], "SELL", price, self.position))
                print(f"🔴 SELL {self.position} shares at {price:.2f} on {self.data.index[i].date()}")
                self.position = 0

In [121]:
class Strategy:
    def __init__(self, data):
        self.data = data
        self.position = 10
        self.cash = 0
        self.trades = []

    def close_position(self):
        if self.position > 0:
            last_price = self.data["Close"].iloc[-1]
            last_index = self.data.index[-1]
            last_date = last_index.date() if isinstance(last_index, pd.Timestamp) else last_index

            self.cash += self.position * last_price
            self.trades.append((last_index, "FORCED SELL", last_price, self.position))
            print(f"⚠️ FORCED SELL {self.position} shares at ${last_price:.2f} on {last_date}")
            self.position = 0

In [122]:
def evaluate(self):
        final_value = self.cash
        profit_loss = final_value - self.budget
        print("\n📊 Strategy Evaluation:")
        print(f"Initial Budget: ${self.budget:.2f}")
        print(f"Final Value:   ${final_value:.2f}")
        print(f"Net P/L:       ${profit_loss:.2f}")
        return final_value, profit_loss, self.trades

In [124]:
import yfinance as yf
import pandas as pd

class TradingStrategy:
    def __init__(self, symbol: "AAPL", start_date: "2018/1/1", end_date: "2023/12/31", budget: float = "5000"):
        """
        Initialize trading strategy with parameters.
        """
        self.symbol = symbol.upper()
        self.start_date = "2018/1/1"
        self.end_date = "2023/12/31"
        self.budget = "5000"
        self.data = None
        self.position = 0
        self.cash = "5000"
        self.trades = []

In [125]:
data = yf.download('AAPL', start="2018-01-01", end="2023-12-31")
data

C:\Users\user\AppData\Local\Temp\ipykernel_3136\2024759451.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download('AAPL', start="2018-01-01", end="2023-12-31")
[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open     Volume
Ticker            AAPL        AAPL        AAPL        AAPL       AAPL
Date
2018-01-02   40.381001   40.390379   39.677744   39.888723  102223600
2018-01-03   40.373959   40.917812   40.310668   40.444285  118071600
2018-01-04   40.561497   40.664642   40.338800   40.446630   89738400
2018-01-05   41.023308   41.110042   40.566192   40.657615   94640000
2018-01-08   40.870926   41.166292   40.772467   40.870926   82271200
...                ...         ...         ...         ...        ...
2023-12-22  191.974670  193.769472  191.349955  193.541392   37149600
2023-12-26  191.429291  192.262235  191.211137  191.984587   28919300
2023-12-27  191.528442  191.875510  189.485739  190.873995   48087700
2023-12-28  191.954849  193.025784  191.548288  192.510145   34049900
2023-12-29  190.913651  192.767946  190.120364  192.272144   42672100

[1509 rows x 5 columns]

In [126]:
def clean_data(self):
        if self.data is not None:
            self.data = self.data[~self.data.index.duplicated(keep="first")]
            self.data = self.data.fillna(method="ffill")  # Forward fill missing values
        return self.data

In [127]:
def compute_indicators(self):
        self.data["MA50"] = self.data["Close"].rolling(window=50).mean()
        self.data["MA200"] = self.data["Close"].rolling(window=200).mean()
        return self.data